### ISSUE TITLE
Chamber Temp Not Showing On Sidebar Graph

### ISSUE THREAD

**Issue by jasonhamilton** [jneilliii/OctoPrint-SideBarTempGraph#10]

**Comment by jasonhamilton** [comment]
<img width="974" alt="Screen Shot 2020-04-20 at 12 09 57 PM" src="https://user-images.githubusercontent.com/388840/79790016-f6605080-82ff-11ea-87e4-1d9b3abd5099.png">

**Comment by jneilliii** [comment]
I'll look into this. I never had that so wasn't part of my development at the time. Probably just need to update my view model to match the current temperature view model as I believe that is relatively new to OctoPrint as well and my original was a clone of what was their at the time.

**Comment by jasonhamilton** [comment]
Thanks.  I'm happy to take a crack at it once I familiarize myself with the code.  I wasn't sure if it was just a quick fix or not.

**Comment by jneilliii** [comment]
It shouldn't be too difficult. It's just a matter of merging whatever changes since 2 years ago into [this](https://github.com/jneilliii/OctoPrint-SideBarTempGraph/blob/master/octoprint_sidebartempgraph/static/js/sidebartempgraph.js) file from the OctoPrint termerature viemwodel code. Will probably take me a few minutes to update.

**Comment by jneilliii** [comment]
Just pushed an update that looks to have solved this in my virtual environment. I'll make it official release once I hear back from you that it works as expected. Use the URL below in plugin manager to update to this version and test. Thanks.

https://github.com/jneilliii/OctoPrint-SideBarTempGraph/archive/0.1.5.zip

**Comment by jasonhamilton** [comment]
Awesome!  I have a print finishing up in a few hours and will try it when it's done.

**Comment by jasonhamilton** [comment]
Works perfectly!  Thanks!!
