### ISSUE TITLE
SideBarTempGraph broken after Octoprint 1.41 update

### ISSUE THREAD

**Issue by PRGeno** [jneilliii/OctoPrint-SideBarTempGraph#12]
Updated Octoprint on two systems and SideBarTempGraph no longer displays anything since upgrading on either system.  
I really like this plugin and I hope it is still going to be supported in the future.

**Comment by jneilliii** [comment]
I'll look into the issue. As for Python compatibility, it is Python 3 compatible as flagged [here](https://github.com/jneilliii/OctoPrint-SideBarTempGraph/blob/8fd962c84e3da328488b36b1eeae682100295096/octoprint_sidebartempgraph/__init__.py#L40) and [here](https://plugins.octoprint.org/plugins/sidebartempgraph/).

**Comment by PRGeno** [comment]
Yes, I saw it had been updated for Python3 after I first posted so I cam back and removed that part hoping before you saw it.  I guess I didn't make it in time and I should have done a better check before I posted.

Thanks for looking into this as your plugin is an extremely useful part of my OctoPrint installations.  I can provide more information about the other loaded plugins if that might help identify any incompatibilities.  I am also still using Python 2.7.x on these two installations if that provides any additional insight.

**Comment by jneilliii** [comment]
No worries. I've been able to reproduce the issue and think it's because of changes to initialization of the page I believe in the new version. If I'm not mistaken, I just need to force a size on the graph so it can initialize properly. More to come once I've had some time to dig a little deeper.

**Comment by jneilliii** [comment]
New release just pushed that should fix this for you @PRGeno. You may have to force a check for update in the advanced section of software update in OctoPrint's settings to see the new release.

**Comment by PRGeno** [comment]
I just updated and my OctoPrint life is whole again.

Thank you so much for your quick response and for making all these fantastic plugins for the community.
