### ISSUE TITLE
Could not parse output from pip...

### ISSUE THREAD

**Issue by wschmeck** [jneilliii/OctoPrint-SideBarTempGraph#4]
Installing the plugin from "https://github.com/jneilliii/OctoPrint-SideBarTempGraph/archive/master.zip"" failed: Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

[plugin_pluginmanager_console.log](https://github.com/jneilliii/OctoPrint-SideBarTempGraph/files/2074325/plugin_pluginmanager_console.log)

Am I the only one???

Walter

**Comment by jneilliii** [comment]
As far as I know you're the first to have an issue with install. Try restarting your octoprint and log back in.
