### ISSUE TITLE
Unsuccessful uninstall

### ISSUE THREAD

**Issue by Mungbeanz** [jneilliii/OctoPrint-SideBarTempGraph#5]
I installed this plugin to test but decided for some of my handheld devices this created too much scrolling.  I went to uninstall, the plugin successfully uninstalls and is removed from the list.  SSH and command prompt shows the same thing. But the plugin is still present on the main page even after full browser cache clear etc.
![1](https://user-images.githubusercontent.com/33512163/42722002-5b80025e-8798-11e8-8be2-ce78f2d8bf88.PNG)
![2](https://user-images.githubusercontent.com/33512163/42722003-5e7d3b52-8798-11e8-801d-ddfb7009c52a.PNG)

**Comment by jneilliii** [comment]
Not sure if this is it but check the next pages for Sidebar Temp Graph. Your screenshot is only up to the letter p. Also, if you turn themeify off in plugin manager does it make a difference?

**Comment by Mungbeanz** [comment]
I thought something called navbar side temp graph was there.  I found another called sidebar temp graph that is not able to be uninstalled.
![3](https://user-images.githubusercontent.com/33512163/42723566-58984ba2-87b4-11e8-9f85-158876a0bfb6.PNG)

I did a bit more than before.  Tried uninstalling normally, in safe mode and in SSH and also cleared browser cache and used a whole other device that has not been used to communicate with this octoprint server before.  All says same error and the plugin is still hanging around both in plugin list and in the side bar.

**Comment by jneilliii** [comment]
Let me do some searching.  Seems like there is a disconnect between what's installed and what octoprint has cached. If you ssh to your pi and run the following command, what is returned in your list?

```
~/oprint/bin/pip freeze
```

**Comment by Mungbeanz** [comment]
Hi,  
thanks for getting back to me.  
When I run that this is returned:

OctoPrint-SibeBarTempGraph==0.1.1

**Comment by jneilliii** [comment]
ok, so run the following while not printing and it should remove the sidebar graph upon next reload of the page.
```
~/oprint/bin/pip uninstall -y OctoPrint-SibeBarTempGraph 
sudo service octoprint restart
```

**Comment by Mungbeanz** [comment]
Yup, works perfect thanks for the help.
