### ISSUE TITLE
Link to "Homepage" in OctoPrint is incorrect

### ISSUE THREAD

**Issue by giberti** [jneilliii/OctoPrint-SideBarTempGraph#7]
![screen shot 2019-01-30 at 12 04 54 pm](https://user-images.githubusercontent.com/771060/52002350-5fec0900-2487-11e9-806e-eba155586375.png)

`Homepage` links to `https://github.com/jneilliii/OctoPrint-SibeBarTempGraph`, notice the `b` in the repo name: Si**b**eBarTempGraph

**Comment by jneilliii** [comment]
Thanks for the heads up.  This has been fixed in version 0.1.3 just released.
