### ISSUE TITLE
Exit Mouseover Problem

### ISSUE THREAD

**Issue by FredGenius** [jneilliii/OctoPrint-SideBarTempGraph#8]
I love this plugin, but I've noticed a small problem (Windows 7, Chrome) - sometimes the numbers stick where the mouse pointer last was, giving a false indication of the current temperatures. If you could make it so when the control loses focus it shows the current temperatures, would be perfect.

**Comment by jneilliii** [comment]
That;s odd.  I just looked and on Windows 10, Chrome I can't reproduce this issue.  As soon as the mouse goes off the graph it immediately goes back to the current temperatures.  Have you noticed any common method in which you can make this happen or help me reproduce the issue?

**Comment by FredGenius** [comment]
I’ve also tried to reproduce the issue but so far without success. It happened again just after I raised the issue the other day, might be when I’ve switched to another Chrome tab and switched back again. I’ll observe more carefully and report back.

 

Thanks,

 

Fred Ö¿Ö

**Comment by FredGenius** [comment]
Happened again recently, after connecting to printer - I set the hot end temp to 230°C, switched to the control tab and went to change filament, came back and the sidebar numerical value was still showing 21°C until mouseover. 

I know this is a hard one to pin down, is there a way to disable the mouseover event? It's not a feature I would miss tbh, far more important to be able to trust the data...

**Comment by FredGenius** [comment]
Screenshot attached showing instance of problem with BOTH temp graphs - maybe a problem with Octoprint?

![Sidebar Sanpshot01](https://user-images.githubusercontent.com/30202455/56266810-08078a80-60e5-11e9-8067-e9573f1877ae.JPG)

**Comment by jneilliii** [comment]
Yeah, if it's happening in the main graph then it could definitely be a core octoprint issue. The only way to know for sure though is to run octoprint in safe mode without any plugins loaded and see if it does the same thing.
